services:
  protection-relay:
    image: ghcr.io/felixhertweck/ocelot-protection-relay-emulator:main
    container_name: protection-relay-emulator
    ports:
      - "10102:102"
    restart: unless-stopped
