name: ot-gateway.yml
on:
  push:
    branches: [ "main" ]
    paths:
      - "ot-gateway/**"
      - "!ot-gateway/**/*.md"
      - ".github/workflows/*"
    tags:
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ot-gateway/**"
      - "!ot-gateway/**/*.md"
      - ".github/workflows/*"
  workflow_dispatch:

permissions:
  contents: read


jobs:
  maven:
    uses: ./.github/workflows/maven.yml
    permissions:
      contents: write
      security-events: write
      actions: read
    with:
      working-directory: ot-gateway
      build-artifact-name: ot-gateway
      build-artifact-path: ot-gateway/target

  backend-docker:
    needs: maven
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: ot-gateway
      build-artifact-path: ot-gateway/target
      docker-file-path: ot-gateway/Dockerfile
      docker-build-context: ot-gateway
      container-image-title: ot-gateway
      image-name: ${{ github.repository }}-ot-gateway