name: OT-Management-Gateway — Build & Publish

on:
  push:
    branches: ["main"]
    paths:
      - "ot-management-gateway/**"
      - "!ot-management-gateway/**/*.md"
      - ".github/workflows/ot-management-gateway.yml"
    tags:
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: ["main"]
    paths:
      - "ot-management-gateway/**"
      - "!ot-management-gateway/**/*.md"
      - ".github/workflows/ot-management-gateway.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      docker-file-path: ot-management-gateway/Dockerfile
      docker-build-context: ot-management-gateway
      container-image-title: ot-management-gateway
      image-name: ${{ github.repository }}-ot-management-gateway
